tools:
    external_code_coverage: true

filter:
    paths:
        - "src/*"
    excluded_paths:
        - "src/CodeGeneration/Fixtures/*"
        - "src/Integration/*"
        - "src/*Test.php"

checks:
    php:
        duplication: false

build:
    nodes:
        analysis:
            tests:
                override:
                    - phpcs-run