tools:
    external_code_coverage: true

filter:
    paths:
        - "src/*"
    excluded_paths:
        - "src/EventSourcing/CodeGeneration/Fixtures/*"
        - "src/EventSourcing/Integration/*"
        - "src/*Test.php"

checks:
    php:
        duplication: false